### ISSUE TITLE
cfengine files are incorrectly copied

### ISSUE THREAD

**Issue by viq** [nmische/kitchen-cfengine#4]
I'm still investigating that, but for example with the default location of `test/cfengine_files/input/my_test.cf` it will properly end up on VM as `/tmp/kitchen/input/my_test.cf`, but on subsequent converge (without destroying the machine or removing any files) it will get copied as `/tmp/kitchen/cfengine_files/input/my_test.cf`. The driver copies all files from `/tmp/kitchen` into `/var/cfengine`, but since the path varies, the new policy files don't end up in correct location.

It's most likely something in https://github.com/nmische/kitchen-cfengine/blob/master/lib/kitchen/provisioner/cfengine.rb#L86 but I don't really know enough ruby to know how to fix this.

**Comment by nmische** [comment]
Not sure what is going on there. I can't say I've noticed that behavior so I'll have to take a look.

**Comment by viq** [comment]
If it matters, I'm using kitchen with RVM and ruby 2.2.0

**Comment by viq** [comment]
Any luck?

**Comment by nmische** [comment]
Sorry, I should have time to look at this in the next few days.

**Comment by viq** [comment]
I tried looking at it, but my (non-existent) ruby skills are not enough for it. Did you manage to find something useful?

**Comment by nmische** [comment]
I'm able to reproduce. Still not sure what the issue is.

**Comment by nmische** [comment]
I may be on to something. I need to make some code changes and do some additional testing. It may be a day or two before I have an update.

**Comment by viq** [comment]
Awesome, thank you!

viq

**Comment by nmische** [comment]
I think this is fixed. Let me know if otherwise.

**Comment by viq** [comment]
Indeed in my simple test it works, thank you!
